site_name: Sycamore の Library
site_author: Sycamore
repo_url: https://nonesycamore.github.io/MyLibrary
theme:
    name: material
    palette:
        scheme: slate
        primary: blue grey
        accent: indigo
    language: zh
    favicon: images\default_icons\favicon.png

extra:
    generator: false
    social:
        - icon: fontawesome/brands/git
          link: https://github.com/nonesycamore/MyLibrary
          name: Source Code in Github
        - icon: fontawesome/brands/github
          link: https://github.com/nonesycamore
          name: SycamoreのGithub
        - icon: fontawesome/brands/docker
          link: https://hub.docker.com/repository/docker/nonesycamore/mydocker-image
          name: SycamoreのDocker Hub

copyright: Copyright &copy; 2022 - Sycamore
markdown_extensions:
    - toc:
        permalink: True
    - footnotes
    - tables
    - md4mathjax
    - mkpatcher
    - markdown_cjk_spacing.cjk_spacing
nav:
    - Home: index.md
    - Math_modeling:
        - Math_modeling/Starting.md
        - Math_modeling/Assignment 1.md
    - Scrips:
        - Scrips/Starting.md
        - CTF_quiz:
            - Crypto:
                - Multiple_Chaos_Maps:
                    - Scrips/CTF_quiz/Crypto/Multiple_Chaos_Maps/exp.md
                    - Scrips/CTF_quiz/Crypto/Multiple_Chaos_Maps/chaos.md
                - Random_predict:
                    - Scrips/CTF_quiz/Crypto/Random_predict/task.md
                    - Scrips/CTF_quiz/Crypto/Random_predict/exp.md
            - Misc:
                - Chaos_and_Pic:
                    - Scrips/CTF_quiz/Misc/Chaos_and_Pic/chaos.md
        - Setup:
            - Scrips/Setup/Docker_Ubuntu1804.md
            - Scrips/Setup/Library_readin.md
            - Scrips/Setup/Ubuntu_AWD.md
            - Scrips/Setup/Ubuntu_Docker.md
            - Scrips/Setup/Ubuntu_zsh.md
            - Scrips/Setup/git_Setup.md
            - Scrips/Setup/Scrips_to_md.md
            - Scrips/Setup/filetree.md
        - CTF_scrips:
            - Scrips/CTF_scrips/Caser_爆破.md
            - Scrips/CTF_scrips/RSA_常见.md
            - Scrips/CTF_scrips/SHA256_验证码爆破.md
            - Scrips/CTF_scrips/base64_多行.md
            - Scrips/CTF_scrips/secret.md
            - Scrips/CTF_scrips/wave_音频处理.md
            - Scrips/CTF_scrips/手机键盘密码.md
