site_name: Sycamore の Library
site_author: Sycamore
repo_url: https://nonesycamore.github.io/MyLibrary
theme:
    name: material
    palette:
        scheme: slate
        primary: blue grey
        accent: indigo
    language: zh
    favicon: images\default_icons\favicon.png

extra:
    generator: false
    social:
        - icon: fontawesome/brands/git
          link: https://github.com/nonesycamore/MyLibrary
          name: Source Code in Github
        - icon: fontawesome/brands/github
          link: https://github.com/nonesycamore
          name: SycamoreのGithub
        - icon: fontawesome/brands/docker
          link: https://hub.docker.com/repository/docker/nonesycamore/mydocker-image
          name: SycamoreのDocker Hub

copyright: Copyright &copy; 2022 - Sycamore
markdown_extensions:
    - toc:
        permalink: True
    - footnotes
    - tables
    - md4mathjax
    - mkpatcher
    - markdown_cjk_spacing.cjk_spacing
nav:
    - Home: index.md
    - Math_modeling:
        - Math_modeling/Starting.md
        - Math_modeling/Assignment 1.md
    - Scrips:
        - Scrips/Starting.md
        - CTF:
            - Scrips/CTF/Caser_爆破.md
            - Scrips/CTF/RSA_常见.md
            - Scrips/CTF/SHA256_验证码爆破.md
            - Scrips/CTF/base64_多行.md
            - Scrips/CTF/secret.md
            - Scrips/CTF/wave_音频处理.md
            - Scrips/CTF/手机键盘密码.md
        - Setup:
            - Scrips/Setup/Docker_Ubuntu1804.md
            - Scrips/Setup/Library_readin.md
            - Scrips/Setup/Ubuntu_AWD.md
            - Scrips/Setup/Ubuntu_Docker.md
            - Scrips/Setup/Ubuntu_zsh.md
            - Scrips/Setup/git_Setup.md
            - Scrips/Setup/Scrips_to_md.md
